[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4"
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py,typing,lint,docs
isolated_build = True

[docker:test-postgres]
image = postgres:11
ports =
    3308:3308/tcp
# Environment variables are passed to the container. They are only
# available to that container, and not to the testenv, other
# containers, or as replacements in other parts of the tox configuration
environment =
    POSTGRES_PASSWORD=INSECURE-PASSWORD
    POSTGRES_USER=gafaelfawr
    POSTGRES_DB=gafaelfawr
    PGPORT=3308
# The healthcheck ensures that tox-docker won't run tests until the
# container is up and the command finishes with exit code 0 (success)
healthcheck_cmd = PGPASSWORD=$POSTGRES_PASSWORD psql \
    --user=$POSTGRES_USER --dbname=$POSTGRES_DB \
    --host=127.0.0.1 --quiet --no-align --tuples-only \
    -1 --command="SELECT 1"
healthcheck_timeout = 1
healthcheck_retries = 30
healthcheck_interval = 1
healthcheck_start_period = 1

[testenv]
description = Run pytest against {envname}.
deps =
    -r{toxinidir}/requirements/main.txt
    -r{toxinidir}/requirements/dev.txt
commands =
    pytest --cov=gafaelfawr --cov-branch --cov-report= -n auto {posargs}
setenv =
    GAFAELFAWR_UI_PATH = {toxinidir}/ui/public

[testenv:coverage-report]
description = Compile coverage from each test run.
skip_install = true
deps = coverage[toml]>=5.0.2
depends =
    py
commands = coverage report

[testenv:typing]
description = Run mypy.
commands =
    mypy src/gafaelfawr tests setup.py

[testenv:lint]
description = Lint codebase by running pre-commit (Black, isort, Flake8).
skip_install = true
deps =
    pre-commit
commands = pre-commit run --all-files

[testenv:docs]
description = Build documentation (HTML) with Sphinx.
whitelist_externals =
    convert
    mv
commands =
    python docs/_static/architecture.py
    seqdiag docs/_static/flow.diag
    seqdiag docs/_static/flow-oidc.diag
    convert -background white -alpha remove -alpha off docs/_static/flow.png docs/_static/flow-fixed.png
    mv docs/_static/flow-fixed.png docs/_static/flow.png
    convert -background white -alpha remove -alpha off docs/_static/flow-oidc.png docs/_static/flow-oidc-fixed.png
    mv docs/_static/flow-oidc-fixed.png docs/_static/flow-oidc.png
    sphinx-build -n -T -b html -d {envtmpdir}/doctrees docs docs/_build/html

[testenv:run]
description = Run the development server with auto-reload for code changes.
usedevelop = true
whitelist_externals =
    docker-compose
commands_pre =
    docker-compose up -d
    holdup -t 60 -T 5 -i 1 -n tcp://localhost:6379/
    holdup -t 60 -T 5 -i 1 -n tcp://localhost:5432/
commands =
    gafaelfawr init
    gafaelfawr run
commands_post =
    docker-compose down
setenv = GAFAELFAWR_SETTINGS_PATH = {toxinidir}/examples/gafaelfawr-dev.yaml
"""

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:"
]

[tool.black]
line-length = 79
target-version = ["py38"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
# Use single-quoted strings so TOML treats the string like a Python r-string
# Multi-line strings are implicitly treated by black as regular expressions

[tool.isort]
include_trailing_comma = true
multi_line_output = 3
known_first_party = ["gafaelfawr", "tests"]
skip = ["docs/conf.py"]
